---
version: '3'
services:
  sonagent:
    image: ghcr.io/sonnhfit/sonagent/sonagent:latest
    env_file:
      - .env
    restart: unless-stopped
    container_name: sonagent
    volumes:
      - "./user_data:/sonagent/user_data"
      - "./user_data/.env:/sonagent/.env"
    ports:
      - "0.0.0.0:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      run
      --config /sonagent/user_data/config.json
      --agentdb sqlite:///user_data/agentdb.db
      --memory-url /sonagent/user_data/memory
